# Site settings
title: 小李子
SEOTitle: 小李子 - 今天努力一点
header-img: img/post-bg-desk.jpg
email: leezxiang@163.com
description: "朝花夕拾"
keyword: "小李子, 技术, 学习笔记, 博客"
url: "https://xleeds.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/xleeds/xleeds.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "四季轮转的天地，或冰与火的乐章"
sidebar-avatar: /img/about-xlz.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
github_username:    xleeds
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 29e7e1f797e0333941f0                            #生成的clientID
  clientSecret: 6e582921f23da29aa83ea70159bc2d54e078bfc5    #生成的clientSecret
  repo: xleeds.github.io    #仓库名称
  owner: xleeds    #github用户名
  admin: xleeds
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b2a6c57dea17b89afa173cbd5b594e2b

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接，请尽量不要删除，谢谢！
friends: [
    {
        title: "Java Family",
        href: "https://github.com/AobingJava/JavaFamily"
    },{
        title: "Java 3y",
        href: "https://github.com/ZhongFuCheng3y/3y"
    }
]
